name: jPatron Master Build
on:
  push:
    branches:
      - main
    tags-ignore:
      - jPatron-*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout jPatron Source Code
      uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
        cache: 'maven'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: CI_DEPLOY_USERNAME # env variable for username in deploy
        server-password: CI_DEPLOY_PASSWORD # env variable for token in deploy
        gpg-private-key: ${{ secrets.OSSRH_GPG_SIGNING_KEY_TEXT }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: Deploy Snapshots with Maven
      run: mvn deploy -B -e --file pom.xml -s .maven-settings.xml -DretryFailedDeploymentCount=10
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SIGNING_KEY_PASSPHRASE }}
