name: jPatron Manual Deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The 'git-ref' to checkout when running Maven deploy."
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout jPatron source code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure GPG Key
        run: |
          # Install gpg secret key
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG
        env:
          GPG_SIGNING_KEY: ${{secrets.OSSRH_GPG_SIGNING_KEY_BASE64}}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: 'temurin'

      - name: Deploy with Maven
        run: > 
            mvn deploy -B -e -P release --file pom.xml -s .maven-settings.xml
            -Dgpg.passphrase=${{secrets.OSSRH_GPG_SIGNING_KEY_PASSPHRASE}}
            -DretryFailedDeploymentCount=10
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
